import os
import sys
import json
import re
import time
from datetime import datetime, timezone

# ANSI Color & Styling Tokens
RESET   = "\033[0m"
BOLD    = "\033[1m"
DIM     = "\033[2m"
RED     = "\033[38;5;196m"
GREEN   = "\033[38;5;48m"
CYAN    = "\033[38;5;51m"
AMBER   = "\033[38;5;214m"
MAGENTA = "\033[38;5;201m"
GRAY    = "\033[38;5;242m"

BANNER = f"""{CYAN}{BOLD}
  █████╗ ██████╗  █████╗  ██████╗██╗  ██╗███╗   ██╗███████╗
 ██╔══██╗██╔══██╗██╔══██╗██╔════╝██║  ██║████╗  ██║██╔════╝
 ███████║██████╔╝███████║██║     ███████║██╔██╗ ██║█████╗  
 ██╔══██║██╔══██╗██╔══██║██║     ██╔══██║██║╚██╗██║██╔══╝  
 ██║  ██║██║  ██║██║  ██║╚██████╗██║  ██║██║ ╚████║███████╗
 ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝
{RESET}{AMBER} » ARACHNE-SUPPLYCHAIN: TYPOSQUATTING & AI HALLUCINATION RADAR «{RESET}
"""

class ArachneSupplyChainScanner:
    def __init__(self, config_path="config.json"):
        if not os.path.exists(config_path):
            print(f"{RED}[-] Error: Configuration file '{config_path}' not found.{RESET}")
            sys.exit(1)

        with open(config_path, "r") as f:
            self.config = json.load(f)

        self.popular_pkgs = self.config.get("popular_packages", [])
        self.ai_hallucinations = self.config.get("known_hallucinated_ai_packages", [])
        self.max_distance = self.config.get("max_typosquat_distance", 2)
        self.mitre = self.config.get("mitre_mappings", {})

    def levenshtein_distance(self, s1, s2):
        """Computes edit distance to flag potential typosquatting variations."""
        if len(s1) < len(s2):
            return self.levenshtein_distance(s2, s1)
        if len(s2) == 0:
            return len(s1)

        previous_row = range(len(s2) + 1)
        for i, c1 in enumerate(s1):
            current_row = [i + 1]
            for j, c2 in enumerate(s2):
                insertions = previous_row[j + 1] + 1
                deletions = current_row[j] + 1
                substitutions = previous_row[j] + (c1 != c2)
                current_row.append(min(insertions, deletions, substitutions))
            previous_row = current_row
        return previous_row[-1]

    def scan_manifest(self, manifest_path):
        if not os.path.exists(manifest_path):
            print(f"{RED}[-] Manifest file '{manifest_path}' not found.{RESET}")
            return

        print(BANNER)
        print(f"{BOLD}Target Dependency Manifest:{RESET} {CYAN}{manifest_path}{RESET}\n")

        steps = [
            "Parsing dependency tree and package version constraints",
            "Executing Levenshtein Distance matrix against PyPI/NPM baselines",
            "Cross-referencing packages against known AI-hallucinated registries",
            "Building CycloneDX-compatible Software Bill of Materials (SBOM)"
        ]
        for step in steps:
            time.sleep(0.2)
            print(f"  {CYAN}▸{RESET} {step}...")

        print("\n" + "=" * 85 + "\n")
        print(f"{BOLD}{'PACKAGE NAME':<30} {'VERSION':<12} {'CLASSIFICATION':<24} {'SEVERITY'}{RESET}")
        print("-" * 85)

        findings = []
        parsed_components = []

        with open(manifest_path, "r") as f:
            lines = f.readlines()

        for raw_line in lines:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue

            # Parse package name and version
            match = re.match(r'^([A-Za-z0-9_\-\.]+)(?:([=<>!~]+)(.+))?$', line)
            if not match:
                continue

            pkg_name = match.group(1).lower()
            version_spec = match.group(3) if match.group(3) else "UNPINNED"

            parsed_components.append({"name": pkg_name, "version": version_spec})

            # Check 1: AI Hallucinated Dependency Attack
            if pkg_name in self.ai_hallucinations:
                findings.append({
                    "package": pkg_name,
                    "version": version_spec,
                    "type": "AI Package Hallucination Trap",
                    "severity": "CRITICAL",
                    "mitre": self.mitre.get("AI_HALLUCINATION"),
                    "fix": "Remove package immediately. Verify if this was generated by an unvetted LLM code-assistant."
                })
                print(f"{pkg_name:<30} {version_spec:<12} {RED}{'AI Hallucination':<24}{RESET} {RED}{'CRITICAL'}{RESET}")
                continue

            # Check 2: Typosquatting Check
            typo_target = None
            for pop_pkg in self.popular_pkgs:
                if pkg_name != pop_pkg:
                    dist = self.levenshtein_distance(pkg_name, pop_pkg)
                    if dist <= self.max_distance:
                        typo_target = pop_pkg
                        break

            if typo_target:
                findings.append({
                    "package": pkg_name,
                    "version": version_spec,
                    "type": f"Typosquat of '{typo_target}'",
                    "severity": "CRITICAL",
                    "mitre": self.mitre.get("TYPOSQUATTING"),
                    "fix": f"Replace rogue package '{pkg_name}' with official library '{typo_target}'."
                })
                print(f"{pkg_name:<30} {version_spec:<12} {RED}{f'Typosquat ({typo_target})':<24}{RESET} {RED}{'CRITICAL'}{RESET}")
                continue

            # Check 3: Floating / Unpinned Version Check
            if version_spec == "UNPINNED":
                findings.append({
                    "package": pkg_name,
                    "version": "LATEST",
                    "type": "Unpinned Dependency",
                    "severity": "MEDIUM",
                    "mitre": self.mitre.get("UNPINNED_VERSION"),
                    "fix": f"Pin exact cryptographic version hash or strict pin: '{pkg_name}==x.y.z'."
                })
                print(f"{pkg_name:<30} {version_spec:<12} {AMBER}{'Unpinned Version':<24}{RESET} {AMBER}{'MEDIUM'}{RESET}")
            else:
                print(f"{pkg_name:<30} {version_spec:<12} {GREEN}{'Verified / Clean':<24}{RESET} {GRAY}OK{RESET}")

        # Summary and SBOM Generation
        print("=" * 85)
        print(f"\n{BOLD}Supply Chain Audit Summary:{RESET} Flagged {RED}{len(findings)}{RESET} risk(s) across {len(parsed_components)} dependencies.")

        # Export CycloneDX-compatible SBOM JSON
        sbom_output = {
            "bomFormat": "CycloneDX",
            "specVersion": "1.5",
            "timestamp": datetime.now(timezone.utc).isoformat() + "Z",
            "components": parsed_components,
            "security_findings": findings
        }
        sbom_filename = "sbom_cyclonedx.json"
        with open(sbom_filename, "w") as f:
            json.dump(sbom_output, f, indent=2)

        print(f"{GREEN}[✓] Generated CycloneDX Software Bill of Materials:{RESET} {BOLD}{sbom_filename}{RESET}\n")

        if findings:
            print(f"{AMBER}{BOLD}[🛠️ DEVSECOPS MITIGATION PLAYBOOK]{RESET}")
            for idx, item in enumerate(findings, start=1):
                print(f"  {CYAN}#{idx} [{item['severity']}]{RESET} {BOLD}{item['package']}{RESET} ({item['type']}):")
                print(f"     ├─ MITRE ATT&CK: {item['mitre']}")
                print(f"     └─ Fix Action:   {item['fix']}\n")

if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else "sample_requirements.txt"
    scanner = ArachneSupplyChainScanner()
    scanner.scan_manifest(target)
